### ISSUE TITLE
dateapp.js

### ISSUE THREAD

**Issue by PlinMartinez** [gmoralesc/introduccion-a-node-js#5]
en node 10 me funciona así, sino da fallo esta linea

console.log(dateFns.format(new Date(), "yyyy/MM/dd"));

**Comment by gmoralesc** [comment]
Saludos, disculpa la demora. Esto se debe a un cambio en el API de date-fns, puedes utilizar la versión que está en el libro:

`npm i -S date-fns@1.30.1`

**Comment by gmoralesc** [comment]
The exercises and the book were updated
